Unique Playwright trace names to avoid collisions
I think this is what caused the following error message in [one of the failing checks](https://github.com/pydata/pydata-sphinx-theme/actions/runs/13705550329/job/38329838641#step:5:22) for #2151:

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run